### ISSUE TITLE
Some results sometimes not shown in HTML output

### ISSUE THREAD

**Issue by eweracs** [fonttools/fontbakery#4687]
## Observed behaviour

I've found that, contrary to the log in the terminal (and the result on fontbakery.com), the HTML output does not list some of the results. The result icons are listed in their respective sections, but the sections are otherwise empty:
<img width="302" alt="image" src="https://github.com/fonttools/fontbakery/assets/51919489/9da28c6e-d4ea-4602-bb2a-e6d2c8750039">

## Expected behaviour

The results (most importantly, the FAILs) should be listed in their sections.

## Resources and steps needed to reproduce

I can't provide the file I am working on, but I have noticed this multiple times with numerous files. It works fine on fontbakery.com.

**Comment by guidoferreyra** [comment]
It happens the same to me.

**Comment by eweracs** [comment]
I see where the issue might stem from:

The results are thrown into the "pass" section, also on fontbakery.com:

<img width="484" alt="image" src="https://github.com/fonttools/fontbakery/assets/51919489/42364716-2259-4c81-b79c-e6483ca463a5">

**Comment by guidoferreyra** [comment]
@felipesanches just adding you in case it flew under the radar. I think this is critical, failed checks are been kind of disguissed as PASS since there is no easy way to spot it on the report.

**Comment by guidoferreyra** [comment]
Just bumping this one since this IMO is kind of critical

**Comment by felipesanches** [comment]
I've been trying to replicate this, but I have not seen it happen in any of my attempts. Please try to build a sample font that causes this problem so that I have something to reproduce the bad output and debug the implementation.

I'm moving this to the next milestone, as I'm about to cut a new release now.

**Comment by guidoferreyra** [comment]
Hi @felipesanches, sorry for the delay here are some sample files, fonts and html report. See the sections with fails but not checks details, eg. "head table"

[SampleFiles.zip](https://github.com/user-attachments/files/15793680/SampleFiles.zip)

**Comment by felipesanches** [comment]
ok, I'll inspect these now. Thanks.

**Comment by felipesanches** [comment]
For the v0.12.8 release, I've just removed the conditional that was omitting these results. But I think this is not the correct fix yet. At least you'll see the results, but I think this may cause other results to not be omitted when they should. The template code is a bit messy and I am having a hard time figuring it out. But I'll further inspect this later and try to make a proper fix.

**Comment by felipesanches** [comment]
So, on v0.12.8 you'll see the results. And a better fix is now planned for v0.12.9

**Comment by jenskutilek** [comment]
Just one more thing ... would it be possible to omit the checks that do not have any results to display completely?

I run fontbakery with `--loglevel WARN`, and then have to scroll through pages of check headers even though they don't apply or don't have any WARN, FAIL, FATAL, ERROR results.

This used to be nice and shorter in a previous version :)

![Bildschirmfoto 2024-09-26 um 11 52 19](https://github.com/user-attachments/assets/6efefcb2-f9ac-4983-bb43-d190df9d219d)

**Comment by guidoferreyra** [comment]
I’ve been thinking on this for weeks!

**Comment by simoncozens** [comment]
I fixed that in #4841.

**Comment by jmsole** [comment]
I am still seeing the original issue in [v0.13.0a3](https://github.com/fonttools/fontbakery/releases/tag/v0.13.0a3). Happens when a check has some fonts that PASS and some that get WARN or FAIL (I am currently seeing it with `name/family_and_style_max_length`). Then I only see the section summary, but the check itself is omitted, even though it has some elements that should be reported. The terminal log and markdown reporter don't have this issue.

I've been trying to debug this, but I'm struggling with that a good deal. To me it seems like the issue might be in [`def omitted(result)`](https://github.com/fonttools/fontbakery/blob/83966c8382d5bf92d6d8972dd2ef4ec100a46226/Lib/fontbakery/reporters/html.py#L67), but right now I have no concrete proof.

**Comment by jmsole** [comment]
Ok, I managed to figure out one way to solve the issue. In [`def omitted(result)`](https://github.com/fonttools/fontbakery/blob/83966c8382d5bf92d6d8972dd2ef4ec100a46226/Lib/fontbakery/reporters/html.py#L67) the first check is to see if a result is a cluster of checks and then deal with that. Here I inserted a check to see if any checks in the cluster shouldn't be omitted based on the level, and if so, simply skip the cluster and don't deal with omitting it.

So, quick and dirty the check went from:
```python
if isinstance(result, list):  # I am cluster of checks
    return omitted(result[0])
```
to this horrible thing, sorry:
```python
if isinstance(result, list):
    found = False
    for r in result:
        if not self.omit_loglevel(r["result"]):
            found = True
            break
    if found:
        return
    else:
        return omitted(result[0])
```
That did the trick for me so now checks where only some fonts have issues do show up properly in the html report. Hope this helps in figuring out a proper solution for this issue.

**Comment by simoncozens** [comment]
A slightly less horrible thing would be:

```python
if isinstance(result, list):
    if any(not self.omit_loglevel(r["result"]) for r in result):
        return False
    return omitted(result[0])
```

But the whole thing is cursed anyway.

**Comment by simoncozens** [comment]
In fact I wonder if this would do it

```python
            if isinstance(result, list):  # I am cluster of checks
                return all(omitted(check) for check in result)
```

**Comment by jmsole** [comment]
Yep, that fixes the issue. I'm happy to trial it out and report if there are any unexpected issues with it.

**Comment by guidoferreyra** [comment]
> In fact I wonder if this would do it
> 
> ```python
>             if isinstance(result, list):  # I am cluster of checks
>                 return all(omitted(check) for check in result)
> ```

This worked for me!

**Comment by Hoolean** [comment]
I just encountered this independently in #4892 and spookily arrived at a byte-for-byte identical patch, even down to the variable names 👻 I've put a PR up at #4894 now, so hopefully we can get this landed for the v0.13.0 release.
